### ISSUE TITLE
Can't compile with PHP 5.6beta4

### ISSUE THREAD

**Issue by wagnert** [appserver-io-php/php-ext-appserver#19]
When i try to compile the extension with PHP 5.6beta4 i got the following error message:

``` sh
cc -I. -I/opt/appserver/var/tmp/php-ext-appserver/src -DPHP_ATOM_INC -I/opt/appserver/var/tmp/php-ext-appserver/src/include -I/opt/appserver/var/tmp/php-ext-appserver/src/main -I/opt/appserver/var/tmp/php-ext-appserver/src -I/opt/appserver/include/php -I/opt/appserver/include/php/main -I/opt/appserver/include/php/TSRM -I/opt/appserver/include/php/Zend -I/opt/appserver/include/php/ext -I/opt/appserver/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /opt/appserver/var/tmp/php-ext-appserver/src/appserver.c  -fno-common -DPIC -o .libs/appserver.o
/opt/appserver/var/tmp/php-ext-appserver/src/appserver.c:312:22: error: no member named 'raw_post_data' in 'sapi_request_info'
    SG(request_info).raw_post_data = estrndup(postData, postData_len);
    ~~~~~~~~~~~~~~~~ ^
/opt/appserver/var/tmp/php-ext-appserver/src/appserver.c:313:22: error: no member named 'raw_post_data_length' in 'sapi_request_info'
    SG(request_info).raw_post_data_length = postData_len;
    ~~~~~~~~~~~~~~~~ ^
/opt/appserver/var/tmp/php-ext-appserver/src/appserver.c:317:51: warning: '/*' within block comment [-Wcomment]
        redefine/undefine constant at runtime ... /* }}} */  
                                                  ^
/opt/appserver/var/tmp/php-ext-appserver/src/appserver.c:345:41: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
            if ((defined->module_number == PHP_USER_CONSTANT)) {
                 ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
/opt/appserver/var/tmp/php-ext-appserver/src/appserver.c:345:41: note: remove extraneous parentheses around the comparison to silence this warning
            if ((defined->module_number == PHP_USER_CONSTANT)) {
                ~                       ^                   ~
/opt/appserver/var/tmp/php-ext-appserver/src/appserver.c:345:41: note: use '=' to turn this equality comparison into an assignment
            if ((defined->module_number == PHP_USER_CONSTANT)) {
                                        ^~
                                        =
/opt/appserver/var/tmp/php-ext-appserver/src/appserver.c:376:80: warning: '/*' within block comment [-Wcomment]
        registeres an uploaded file top super global hash table at runtime ... /* }}} */
                                                                               ^
/opt/appserver/var/tmp/php-ext-appserver/src/appserver.c:401:76: warning: '/*' within block comment [-Wcomment]
        gets headers set via header function and reset if flag was set ... /* }}} */
                                                                           ^
/opt/appserver/var/tmp/php-ext-appserver/src/appserver.c:424:72: warning: '/*' within block comment [-Wcomment]
        will reset the headers_sent param to given flag at runtime ... /* }}} */
                                                                       ^
5 warnings and 2 errors generated.
make: *** [appserver.lo] Error 1
```
